<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

    'Login' => 'Войти',
    'Logout' => 'Выйти',
	
    'Home' => 'Главная',
    'About' => 'О проекте',
    'Contact' => 'Контакты',
    'Downloads' => 'Скачать книгу',
    'Send' => 'Отправить',
    
    'Register' => 'Зарегистрировать',
    'Profile' => 'Профиль',
    'Book list' => 'Список книг',
    'Send book' => 'Отправить книгу',
    'Title' => 'Название',
    'Search' => 'Поиск',
    'Name' => 'Имя',
    'Password' => 'Пароль',
    'Confirm Password' => 'Подтвердить пароль',
    'Address' => 'Адрес',
    'Recipients' => 'Получатели',
    'Recipient' => 'Получатель',
    'Add recipient' => 'Добавить получателя',
    'Create recipient' => 'Добавить получателя',
    'Create Recipients' => 'Добавить получателя',
    'Select status' => 'Выберите статус',
	
    'Next' => 'Следующий',
    'Previouse' => 'Предидущий',
    'Bookworld' => 'Книгомир',
    'Download' => 'Скачать',
    'Books statistics' => 'Статистика книг',
	'Country' => 'Страна',
    'Select country' => 'Выберите страну',
    'Region' => 'Регион',
    'Select region' => 'Выберите регион',
    'Number of books' => 'Количество книг',
    'more_info_btn' => 'Узнать больше',
    'Our mission' => 'Наша миссия',
    'Sticker' => 'Наклейка',
    'Control' => 'Контроль',
    'Control panel' => 'Панель управления',
    'Administrator' => 'Администратор',
    'Library' => 'Библиотека',
    'Personal cabinet' => 'Личный кабинет',
    'Surname' => 'Фамилия',
    'Save' => 'Сохранить',
    'Edit' => 'Изменить',
    'ID' => 'Номер',
    'Status' => 'Статус',
    'Where is' => 'Где находится',
    'Unic ID' => 'Уникальный номер',
    'Serch' => 'Поиск',
    'Enter' => 'Ввести',
    'Author' => 'Автор',
    'Remind password' => 'Напомнить пароль',
    'Forgot password?' => 'Забыли пароль?',
    'Remind' => 'Напомнить',
    'Already have account?' => 'Уже есть учётная запись?',
    'Form' => 'Форма',
    'Year' => 'Год',
    'Code' => 'Код',
    
    'field' => 'поле',
    'fill form' => 'заполнить форму',
    'Pick up' => 'Наличие курьера',
    'heading_step_one' => 'НАКЛЕЙКА',
    'heading_step_two' => 'ПЕРЕДАЧА',
    'heading_step_three' => 'КОНТРОЛЬ',
    'text_step_one' => 'Зарегистрируйте книгу и получите уникальный номер-наклейку',
    'text_step_two' => 'Тут можно выбрать получателя и отправить книгу',
    'text_step_three' => 'Узнайте у кого в данный момент находится книга',
    'select' => 'выбор',
    'user_id' => '',
    'user' => 'пользователь',
    'password' => 'пароль',
    'rename' => 'переименовать',
    
    'My Company' => 'Подари Книгу',
    'main_sub_title' => 'На полке залежались прочитанные детские книги? Отдавайте их тем, у кого в силу сложившихся обстоятельств нет возможности иметь “свою” книгу.',
    'main_title' => 'Подари Книгу',
	
	'View' => 'Просмотреть',
	'Create' => 'Добавить',
	'Update' => 'Редактировать',
	'Delete' => 'Удалить',
	
    'Books' => 'Книги',
    'Create Books' => 'Добавить книгу',
    'Create book' => 'Добавить книгу',
	'Select year' => 'Выберите год',
	
    'text_info' => 'Зарегистрируйтесь чтобы воспользоваться сайтом. Это бесплатно',
    'Users' => 'Пользователи',
    'Create Users' => 'Добавить пользователя',
    'Create user' => 'Добавить пользователя',
    'Select user' => 'Выберите пользователя',
    'Email Verified' => 'Подтверждённый?',
    'Verification Token' => 'Токен',
    'Blocked' => 'Заблокирован?',
    'Yes' => 'Да',
    'No' => 'Нет',
	
	
    'My Account' => 'Личный кабинет',
    'Profile' => 'Профиль',
    'My Books' => 'Мои книги',
	
    'cpanel' => 'Панель управления',
    'step_one_btn' => 'Добавить книгу',
    'step_two_btn' => 'Отправить книгу',
    'step_three_btn' => 'Найти книгу',
    'about_main_text' => 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim',
    
    'Subject' => 'Тема',
    'Verification Code' => 'Код',
    'Message' => 'Сообщение',
    'E-mail' => 'Электронная почта',
    'Sign up' => 'Зарегистрироватся',   
    'thank_you_for_contacting_text' => 'Спасибо, сообщение отправлено.',
    'thank_you_for_registration_text' => 'Спасибо за регистрацию.',
    'Submit' => 'Отправить',
    'Username' => 'Логин',
    'Remember Me' => 'Запомнить меня',
    'Incorrect username or password.' => 'Неправильный пароль',
    'Data updated successfully!' => 'Данные обновлены успешно!',
    'statistics_main_text' => 'Количество книг отправленых в странах',
    'Sent' => 'Отправленные',
    'Created' => 'Добавлено',
    'Amount' => 'Количество',
    '' => '',
];
